package pers.zhentao.springandmybatis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.zhentao.springandmybatis.pojo.FilmText;
import pers.zhentao.springandmybatis.pojo.FilmTextExample;

public interface FilmTextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated
     */
    int countByExample(FilmTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated
     */
    int deleteByExample(FilmTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Short filmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated
     */
    int insert(FilmText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated
     */
    int insertSelective(FilmText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated
     */
    List<FilmText> selectByExampleWithBLOBs(FilmTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated
     */
    List<FilmText> selectByExample(FilmTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated
     */
    FilmText selectByPrimaryKey(Short filmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FilmText record, @Param("example") FilmTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") FilmText record, @Param("example") FilmTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FilmText record, @Param("example") FilmTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FilmText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(FilmText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FilmText record);
}