package pers.zhentao.springandmybatis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.zhentao.springandmybatis.pojo.FilmCategory;
import pers.zhentao.springandmybatis.pojo.FilmCategoryExample;
import pers.zhentao.springandmybatis.pojo.FilmCategoryKey;

public interface FilmCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_category
     *
     * @mbggenerated
     */
    int countByExample(FilmCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_category
     *
     * @mbggenerated
     */
    int deleteByExample(FilmCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(FilmCategoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_category
     *
     * @mbggenerated
     */
    int insert(FilmCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_category
     *
     * @mbggenerated
     */
    int insertSelective(FilmCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_category
     *
     * @mbggenerated
     */
    List<FilmCategory> selectByExample(FilmCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_category
     *
     * @mbggenerated
     */
    FilmCategory selectByPrimaryKey(FilmCategoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FilmCategory record, @Param("example") FilmCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FilmCategory record, @Param("example") FilmCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FilmCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FilmCategory record);
}