package pers.zhentao.springandmybatis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.zhentao.springandmybatis.pojo.FilmActor;
import pers.zhentao.springandmybatis.pojo.FilmActorExample;
import pers.zhentao.springandmybatis.pojo.FilmActorKey;

public interface FilmActorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_actor
     *
     * @mbggenerated
     */
    int countByExample(FilmActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_actor
     *
     * @mbggenerated
     */
    int deleteByExample(FilmActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_actor
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(FilmActorKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_actor
     *
     * @mbggenerated
     */
    int insert(FilmActor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_actor
     *
     * @mbggenerated
     */
    int insertSelective(FilmActor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_actor
     *
     * @mbggenerated
     */
    List<FilmActor> selectByExample(FilmActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_actor
     *
     * @mbggenerated
     */
    FilmActor selectByPrimaryKey(FilmActorKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_actor
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FilmActor record, @Param("example") FilmActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_actor
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FilmActor record, @Param("example") FilmActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_actor
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FilmActor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_actor
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FilmActor record);
}