package pers.zhentao.springandmybatis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.zhentao.springandmybatis.pojo.Language;
import pers.zhentao.springandmybatis.pojo.LanguageExample;

public interface LanguageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated
     */
    int countByExample(LanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated
     */
    int deleteByExample(LanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Byte languageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated
     */
    int insert(Language record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated
     */
    int insertSelective(Language record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated
     */
    List<Language> selectByExample(LanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated
     */
    Language selectByPrimaryKey(Byte languageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Language record, @Param("example") LanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Language record, @Param("example") LanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Language record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Language record);
}